### ISSUE TITLE
Query string

### ISSUE THREAD

**Issue by Prince2k3** [ilia3546/Graphus#2]
I'm trying to send a query and I used the debug output with the client and noticed that what it is sending is not what the server expects.

for example 

Server expects 
```GraphQL
query SongsByAlbumID($albumId: ID!) {
    findSongsByAlbumID(albumId: $albumId) {
        __typename
        id
        albumId
        songName
    }
}
```

What is sent by Graphus

```GraphQL
query {
   findSongsByAlbumID(albumId: "tc2c5e86-f2fe-3029-h4fb-244c6c2721c3" ) {
       id
       albumId
       songName
  }
}
```
Seems to be missing the `SongsByAlbumID($albumId: ID!)` which I don't know how to define it.

**Comment by ilia3546** [comment]
Hello! Named queries usually are used when you want to pass variables into already prepared query. I’m sure that your example will be correctly processed by the server. Your server sent some kind of error?

**Comment by Prince2k3** [comment]
That's what I'm thinking but I am not getting the message of what is wrong

**Comment by Prince2k3** [comment]
@ilia3546 So the second item works. I tested it in Postman and data shows up with no errors. I guess my issue then is parsing the data is just coming back as null

**Comment by Prince2k3** [comment]
Found the issue! I needed a url session configuration with an Authorization header setup in it.
